blueprint:
  name: Import Alexa shoppinglist DWE11
  description: Import Alexa shopping to your Home Assistant shopping list.
  domain: automation
  author: DWE11
  input:
    webhook_trigger:
      name: Webhook Trigger
      description: "Please create a webhook trigger. Other triggers are not supported!"
      selector:
        trigger: {}
    shopping_list:
      name: Shopping List
      description: Which shopping list should receive the entries from the Alexa shopping list?
      selector:
        entity:
          filter:
            domain: todo
variables:
  shopping_list: !input shopping_list
  trigger: !input webhook_trigger
trigger_variables:
  webhook_id_variable: !input webhook_trigger
triggers:
  - trigger: webhook
    webhook_id: "import-alexa-shoppinglist-yfI_vEehWDOZ127o9GANwjF6"
    allowed_methods:
      - POST
      - PUT
    local_only: true
actions:
  - action: todo.get_items
    metadata: {}
    data: {}
    response_variable: list
    target:
      entity_id: !input shopping_list
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.json.name not in
              list[shopping_list]["items"] |
              map(attribute="summary") | list }}
        sequence:
          - action: todo.add_item
            target:
              entity_id: !input shopping_list
            metadata: {}
            data:
              item: "{{ trigger.json.name }}"
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.json.name in list[shopping_list]["items"] |
              map(attribute="summary") | list }}
        sequence:
          - action: todo.update_item
            target:
              entity_id: !input shopping_list
            metadata: {}
            data:
              item: "{{ trigger.json.name }}"
              status: needs_action
mode: single
max: 100
